name: Gold BigQuery Table

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: temporary-dataproc-bucket
      SCHEMA_FILE: schemas/ridership_schema.json
      BQ_TABLE_NAME: nyc  # Customize your BQ table name here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create JSON Credentials File
        id: create-json-credentials
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "gcloud-service-key.json"
          json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Create GCS Bucket if not exists
        run: |
          if ! gsutil ls -b gs://$BUCKET_NAME &>/dev/null; then
            echo "Creating bucket: $BUCKET_NAME"
            gsutil mb -l US gs://$BUCKET_NAME
          else
            echo "Bucket already exists: $BUCKET_NAME"
          fi

      - name: Create BigQuery Table
        run: |
          bq mk --table \
            ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.BQ_DATASET }}.$BQ_TABLE_NAME \
            $SCHEMA_FILE
